In [8]:
import numpy as np
import pandas as pd
import seaborn as sns

In [9]:
df = pd.DataFrame({"gruplar" : ["A","B","C","A","B","C"],
                  "veri" : [10,11,52,23,43,55] })
df

  gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [10]:
df.groupby("gruplar").mean()
#gruplar sütunundaki aynı olan değerleri buldu ve onları grupladı ve ortalamasını aldı(diğer toplulaştırma işlemleri de kullanılabilir)

         veri
gruplar
A        16.5
B        27.0
C        53.5

In [11]:
df2 = sns.load_dataset("planets")
df2

               method  number  orbital_period    mass  distance  year
0     Radial Velocity       1      269.300000   7.100     77.40  2006
1     Radial Velocity       1      874.774000   2.210     56.95  2008
2     Radial Velocity       1      763.000000   2.600     19.84  2011
3     Radial Velocity       1      326.030000  19.400    110.62  2007
4     Radial Velocity       1      516.220000  10.500    119.47  2009
5     Radial Velocity       1      185.840000   4.800     76.39  2008
6     Radial Velocity       1     1773.400000   4.640     18.15  2002
7     Radial Velocity       1      798.500000     NaN     21.41  1996
8     Radial Velocity       1      993.300000  10.300     73.10  2008
9     Radial Velocity       2      452.800000   1.990     74.79  2010
10    Radial Velocity       2      883.000000   0.860     74.79  2010
11    Radial Velocity       1      335.100000   9.880     39.43  2009
12    Radial Velocity       1      479.100000   3.880     97.28  2008
13    Radial Velocity       3     1078.000000   2.530     14.08  1996
14    Radial Velocity       3     2391.000000   0.540     14.08  2001
15    Radial Velocity       3    14002.000000   1.640     14.08  2009
16    Radial Velocity       1        4.230785   0.472     15.36  1995
17    Radial Velocity       5       14.651000   0.800     12.53  1996
18    Radial Velocity       5       44.380000   0.165     12.53  2004
19    Radial Velocity       5     4909.000000   3.530     12.53  2002
20    Radial Velocity       5        0.736540     NaN     12.53  2011
21    Radial Velocity       5      261.200000   0.172     12.53  2007
22    Radial Velocity       3        4.215000   0.016      8.52  2009
23    Radial Velocity       3       38.021000   0.057      8.52  2009
24    Radial Velocity       3      123.010000   0.072      8.52  2009
25    Radial Velocity       1      116.688400     NaN     18.11  1996
26    Radial Velocity       1      691.900000     NaN     81.50  2012
27    Radial Velocity       1      952.700000   5.300     97.18  2008
28    Radial Velocity       1      181.400000   3.200     45.52  2013
29            Imaging       1             NaN     NaN     45.52  2005
...               ...     ...             ...     ...       ...   ...
1005          Transit       1        3.693641     NaN    200.00  2012
1006          Transit       1        4.465633     NaN    330.00  2012
1007          Transit       1        4.617101     NaN    255.00  2012
1008          Transit       1        2.838971     NaN    455.00  2012
1009          Transit       1        5.017180     NaN    300.00  2012
1010          Transit       1        7.919585     NaN    125.00  2012
1011          Transit       1        4.305001     NaN    400.00  2012
1012          Transit       1        3.855900     NaN    480.00  2012
1013          Transit       1        4.411953     NaN    160.00  2012
1014          Transit       1        4.378090     NaN    330.00  2012
1015          Transit       1        1.573292     NaN    350.00  2012
1016          Transit       1        2.311424     NaN    310.00  2013
1017          Transit       1        4.086052     NaN    380.00  2012
1018          Transit       1        4.614420     NaN    225.00  2012
1019          Transit       1        2.903675     NaN    345.00  2012
1020          Transit       1        2.216742     NaN    340.00  2012
1021          Transit       1        2.484193     NaN    260.00  2013
1022          Transit       1        1.360031     NaN     93.00  2012
1023          Transit       1        2.175176     NaN    550.00  2012
1024          Transit       1        3.662387     NaN    240.00  2012
1025          Transit       1        3.067850     NaN     60.00  2012
1026          Transit       1        0.925542     NaN    470.00  2014
1027          Imaging       1             NaN     NaN     19.20  2011
1028          Transit       1        3.352057     NaN   3200.00  2012
1029          Imaging       1             NaN     NaN     10.10  2012
1030          Transit       1        3.941507     NaN    172.00  2006
1031          Transit       1        2.615864     NaN    148.00  2007
1032          Transit       1        3.191524     NaN    174.00  2007
1033          Transit       1        4.125083     NaN    293.00  2008
1034          Transit       1        4.187757     NaN    260.00  2008

[1035 rows x 6 columns]

In [21]:
df2.groupby("method").sum()

,number,orbital_period,mass,distance,year
method,,,,,
Astrometry,2,1.262360e+03,0.00000,35.75,4023
Eclipse Timing Variations,15,4.276480e+04,10.25000,1261.44,18090
Imaging,50,1.418973e+06,0.00000,2166.91,76347
Microlensing,27,2.207500e+04,0.00000,41440.00,46225
Orbital Brightness Modulation,5,2.127920e+00,0.00000,2360.00,6035
Pulsar Timing,11,3.671511e+04,0.00000,1200.00,9992
Pulsation Timing Variations,1,1.170000e+03,0.00000,0.00,2007
Radial Velocity,952,4.553151e+05,1341.65638,27348.11,1110158
Transit,776,8.377523e+03,1.47000,134242.77,798461
Transit Timing Variations,9,2.393505e+02,0.00000,3313.00,8050

In [25]:
df2.groupby("method")[["number","distance"]].std()

                                 number     distance
method
Astrometry                     0.000000     4.094148
Eclipse Timing Variations      0.500000   213.203907
Imaging                        0.933035    53.736817
Microlensing                   0.387553  2076.611556
Orbital Brightness Modulation  0.577350     0.000000
Pulsar Timing                  1.095445          NaN
Pulsation Timing Variations         NaN          NaN
Radial Velocity                1.157141    45.559381
Transit                        1.399119   913.876990
Transit Timing Variations      0.500000   915.819487

In [43]:
df2.groupby("method")[["number","distance"]].describe()

                              number                                           \
                               count      mean       std  min  25%  50%   75%
method
Astrometry                       2.0  1.000000  0.000000  1.0  1.0  1.0  1.00
Eclipse Timing Variations        9.0  1.666667  0.500000  1.0  1.0  2.0  2.00
Imaging                         38.0  1.315789  0.933035  1.0  1.0  1.0  1.00
Microlensing                    23.0  1.173913  0.387553  1.0  1.0  1.0  1.00
Orbital Brightness Modulation    3.0  1.666667  0.577350  1.0  1.5  2.0  2.00
Pulsar Timing                    5.0  2.200000  1.095445  1.0  1.0  3.0  3.00
Pulsation Timing Variations      1.0  1.000000       NaN  1.0  1.0  1.0  1.00
Radial Velocity                553.0  1.721519  1.157141  1.0  1.0  1.0  2.00
Transit                        397.0  1.954660  1.399119  1.0  1.0  1.0  2.00
Transit Timing Variations        4.0  2.250000  0.500000  2.0  2.0  2.0  2.25

                                   distance                            \
                               max    count         mean          std
method
Astrometry                     1.0      2.0    17.875000     4.094148
Eclipse Timing Variations      2.0      4.0   315.360000   213.203907
Imaging                        4.0     32.0    67.715937    53.736817
Microlensing                   2.0     10.0  4144.000000  2076.611556
Orbital Brightness Modulation  2.0      2.0  1180.000000     0.000000
Pulsar Timing                  3.0      1.0  1200.000000          NaN
Pulsation Timing Variations    1.0      0.0          NaN          NaN
Radial Velocity                6.0    530.0    51.600208    45.559381
Transit                        7.0    224.0   599.298080   913.876990
Transit Timing Variations      3.0      3.0  1104.333333   915.819487

                                                                        \
                                   min        25%       50%        75%
method
Astrometry                       14.98    16.4275    17.875    19.3225
Eclipse Timing Variations       130.72   130.7200   315.360   500.0000
Imaging                           7.69    22.1450    40.395   132.6975
Microlensing                   1760.00  2627.5000  3840.000  4747.5000
Orbital Brightness Modulation  1180.00  1180.0000  1180.000  1180.0000
Pulsar Timing                  1200.00  1200.0000  1200.000  1200.0000
Pulsation Timing Variations        NaN        NaN       NaN        NaN
Radial Velocity                   1.35    24.4125    40.445    59.2175
Transit                          38.00   200.0000   341.000   650.0000
Transit Timing Variations       339.00   597.0000   855.000  1487.0000


                                   max
method
Astrometry                       20.77
Eclipse Timing Variations       500.00
Imaging                         165.00
Microlensing                   7720.00
Orbital Brightness Modulation  1180.00
Pulsar Timing                  1200.00
Pulsation Timing Variations        NaN
Radial Velocity                 354.00
Transit                        8500.00
Transit Timing Variations      2119.00

In [44]:
df3 = df2.groupby("method").sum()

In [45]:
df3

,number,orbital_period,mass,distance,year
method,,,,,
Astrometry,2,1.262360e+03,0.00000,35.75,4023
Eclipse Timing Variations,15,4.276480e+04,10.25000,1261.44,18090
Imaging,50,1.418973e+06,0.00000,2166.91,76347
Microlensing,27,2.207500e+04,0.00000,41440.00,46225
Orbital Brightness Modulation,5,2.127920e+00,0.00000,2360.00,6035
Pulsar Timing,11,3.671511e+04,0.00000,1200.00,9992
Pulsation Timing Variations,1,1.170000e+03,0.00000,0.00,2007
Radial Velocity,952,4.553151e+05,1341.65638,27348.11,1110158
Transit,776,8.377523e+03,1.47000,134242.77,798461
Transit Timing Variations,9,2.393505e+02,0.00000,3313.00,8050

In [46]:
df3.iloc[:,0:3]

                               number  orbital_period        mass
method
Astrometry                          2    1.262360e+03     0.00000
Eclipse Timing Variations          15    4.276480e+04    10.25000
Imaging                            50    1.418973e+06     0.00000
Microlensing                       27    2.207500e+04     0.00000
Orbital Brightness Modulation       5    2.127920e+00     0.00000
Pulsar Timing                      11    3.671511e+04     0.00000
Pulsation Timing Variations         1    1.170000e+03     0.00000
Radial Velocity                   952    4.553151e+05  1341.65638
Transit                           776    8.377523e+03     1.47000
Transit Timing Variations           9    2.393505e+02     0.00000

In [47]:
df3.loc[:,"number":"distance"]

                               number  orbital_period        mass   distance
method
Astrometry                          2    1.262360e+03     0.00000      35.75
Eclipse Timing Variations          15    4.276480e+04    10.25000    1261.44
Imaging                            50    1.418973e+06     0.00000    2166.91
Microlensing                       27    2.207500e+04     0.00000   41440.00
Orbital Brightness Modulation       5    2.127920e+00     0.00000    2360.00
Pulsar Timing                      11    3.671511e+04     0.00000    1200.00
Pulsation Timing Variations         1    1.170000e+03     0.00000       0.00
Radial Velocity                   952    4.553151e+05  1341.65638   27348.11
Transit                           776    8.377523e+03     1.47000  134242.77
Transit Timing Variations           9    2.393505e+02     0.00000    3313.00